version: '3.9'

services:
  mysqldb:
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    volumes:
      - ./databases.sql:/docker-entrypoint-initdb.d/databases.sql
      - mysqldb_volume:/var/lib/mysql
    networks:
      - mysqldb_network

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - ${ADMINER_PORT}:${ADMINER_PORT}
    networks:
      - mysqldb_network
    depends_on:
      - mysqldb

volumes:
  mysqldb_volume:

networks: 
  mysqldb_network:
    driver: bridge